#! /bin/bash

if [ $# -ne 1 ]
then
	echo "Missing Output File"
fi
rm $1

while read -r line
do
	echo $line >> $1
done

sort -u -o "$1" "$1"
count=$(cat "$1" | wc -l)
orgcount=$(cat "test.dat" | wc -l)

echo "The number of lines in input file: $orgcount" >> $1
echo "The number of lines in $1: $count" >> $1
