#! /bin/bash

if [ $# -ne 1 ]
then
	echo "Missing Output File"
fi
rm $1

while read -r line
do
	echo $line >> $1
done

sort -u -o "$1" "$1"
count=$(cat "$1" | wc -l)

echo "The number of lines in input file: $inputcount" >> $1
echo "The number of lines in output file: $count" >> $1
