#! /bin/bash

if [ $# -ne 1 ]
then
	echo "Missing argument"
	exit 1
fi

while read -r line
do
	#echo $line
	set $line
	flag=1	
	while read filter
	do
		#echo $filter
		if test "$1" = "$filter"
			then
				flag=0
				continue
			else
				continue
		fi

	done < noise.txt
	
	if test $flag -eq 1
		then
			echo $line
	fi
done 
