#! /bin/tcsh

echo "Starting"
if ($# == 0) then
	echo "Must provide paramers"
endif

if ($#argv > 0 && $#argv < 8) then
	set sum = 0
	set avg = 0
	foreach i ($argv[*])
		@ sum += $i
	end
	echo -n "Sum: "
	echo $sum
	@ avg = ($sum)/($#argv)
	echo -n "Average: "
	echo $avg
endif

if ($#argv > 7) then
	echo "Incorrect # of  Parameters"

endif

echo "ending"
